site_name: LUTE
plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [lute]
        options:
          show_source: true
